#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


ENV_FILE=".dev.vars"
TOTAL_STAGES=10

# ── extra helpers (below the marker, wizard-specific) ─────────────────────

# set_jsonc KEY VALUE: replace the first  "KEY": "..."  in wrangler.jsonc.
# Plain IDs / UUIDs / a workers.dev URL only - no awk-sub metacharacters.
set_jsonc() {
  local key="$1" value="$2" tmp
  tmp=$(mktemp)
  awk -v k="\"$key\":" -v v="$value" '
    !done && index($0, k) { sub(/: *"[^"]*"/, ": \"" v "\""); done=1 }
    { print }
  ' wrangler.jsonc > "$tmp" && mv "$tmp" wrangler.jsonc
  printf '  %s✓ set%s wrangler.jsonc %s\n' "$GREEN" "$RESET" "$key"
}

# wr: run wrangler via npx, streaming output.
wr() { npx --yes wrangler "$@"; }

# ct_api PATH: GET the Connecteam API with the captured key.
ct_api() { curl -sS -H "X-API-KEY: $CT_API_KEY" -H "accept: application/json" "https://api.connecteam.com$1"; }

# ct_api_post PATH JSON: POST to the Connecteam API with the captured key.
ct_api_post() {
  curl -sS -X POST -H "X-API-KEY: $CT_API_KEY" -H "content-type: application/json" \
    -H "accept: application/json" -d "$2" "https://api.connecteam.com$1"
}

# put_secret NAME VALUE: pipe a value into `wrangler secret put` (no echo).
put_secret() {
  printf '%s' "$2" | wr secret put "$1" >/dev/null \
    && printf '  %s✓ set%s Cloudflare secret %s\n' "$GREEN" "$RESET" "$1" \
    || warn "could not set secret $1 - run: printf %%s '<value>' | npx wrangler secret put $1"
}

# health_num KEY: print the deployed Worker's /health ops.KEY as an integer
# (0 if the field is absent or /health is unreachable). Needs $WORKER_URL.
health_num() {
  curl -fsS "${WORKER_URL}/health" 2>/dev/null | node -e '
    const key = process.argv[1];
    let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
      try { process.stdout.write(String(Number((JSON.parse(s).ops || {})[key] || 0))); }
      catch (e) { process.stdout.write("0"); }
    });' "$1" 2>/dev/null || printf '0'
}

# ── prerequisites (before the banner, so a missing tool fails fast) ───────
for _c in node npm npx git curl; do
  command -v "$_c" >/dev/null 2>&1 || { printf 'missing required tool: %s\n' "$_c" >&2; exit 1; }
done
grep -q '"name": "eh-webhook"' package.json 2>/dev/null \
  || { printf 'run this from the EH_Webhook repo root\n' >&2; exit 1; }
[[ -d node_modules ]] || { printf 'installing dependencies...\n'; npm install; }

banner "EH_Webhook - client deployment"

# ─────────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
say "This deployment runs on the CLIENT's own Cloudflare account."
say "Queues need the Workers Paid plan (~\$5/mo)."
open_url "https://dash.cloudflare.com/?to=/:account/workers/plans"
confirm "Is this account on the Workers Paid plan?" || { warn "Upgrade first, then re-run."; exit 1; }
say "Logging wrangler in to that account (a browser tab will open)..."
wr whoami >/dev/null 2>&1 || wr login
wr whoami | sed 's/^/  /'
confirm "Is the account above the right one?" || { warn "Run 'npx wrangler logout' then re-run."; exit 1; }

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: API key"
say "Create an API key with read on users + onboarding and write on chat."
open_url "https://app.connecteam.com/#/settings/integrations/api"
step "Navigate to the equivalent of Settings > Integrations > API, create a key."
ask_secret CT_API_KEY "Paste the Connecteam API key:"
write_env CT_API_KEY "$CT_API_KEY"

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: custom publisher"
say "The custom publisher is the sender of every message the sync posts."
open_url "https://app.connecteam.com/#/settings"
step "Navigate to the equivalent of Settings > Feed settings > Custom publishers."
step "Create one named 'EH Sync' and copy its numeric publisher ID."
ask CT_CUSTOM_PUBLISHER_ID "Paste the custom publisher ID:"
write_env CT_CUSTOM_PUBLISHER_ID "$CT_CUSTOM_PUBLISHER_ID"
set_jsonc CT_CUSTOM_PUBLISHER_ID "$CT_CUSTOM_PUBLISHER_ID"

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: alerts channel"
say "A chat channel receives Manual-follow-up notices and System alerts."
say "Create a channel named 'EH Sync Alerts' and add the payroll admins."
pause "Press Enter once the channel exists."
say "Chat channels on this account:"
ct_api "/chat/v1/conversations" \
  | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const c=(JSON.parse(s).data?.conversations)||[];for(const x of c)console.log("   ",x.id,"  ",x.title||x.name||"(untitled)")}catch(e){console.log("   (could not list - open GET /chat/v1/conversations by hand)")}})'
ask ADMIN_CONNECTEAM_CHANNEL_ID "Paste the 'EH Sync Alerts' channel ID:"
write_env ADMIN_CONNECTEAM_CHANNEL_ID "$ADMIN_CONNECTEAM_CHANNEL_ID"
set_jsonc ADMIN_CONNECTEAM_CHANNEL_ID "$ADMIN_CONNECTEAM_CHANNEL_ID"

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: onboarding pack + webhook secret"
say "Onboarding packs on this account:"
ct_api "/onboarding/v1/packs" \
  | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const p=(JSON.parse(s).data?.packs)||(JSON.parse(s).data)||[];for(const x of p)console.log("   ",x.id||x.packId,"  ",x.name||"(unnamed)")}catch(e){console.log("   (could not list - open GET /onboarding/v1/packs by hand)")}})'
ask CT_ONBOARDING_PACK_ID "Paste the onboarding pack ID:"
write_env CT_ONBOARDING_PACK_ID "$CT_ONBOARDING_PACK_ID"
set_jsonc CT_ONBOARDING_PACK_ID "$CT_ONBOARDING_PACK_ID"
CT_WEBHOOK_SECRET=$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')
write_env CT_WEBHOOK_SECRET "$CT_WEBHOOK_SECRET"
say "Generated CT_WEBHOOK_SECRET (used when registering the webhook in the last stage)."

# ─────────────────────────────────────────────────────────────────────────
stage "Employment Hero: API key"
say "Create an API key in Employment Hero Payroll."
open_url "https://api.yourpayroll.com.au"
step "Navigate to the equivalent of Payroll settings > API, create a key."
warn "Also DISABLE the employee self-setup email for the business - the sync fills the record via the API."
ask_secret EH_API_KEY "Paste the Employment Hero API key:"
write_env EH_API_KEY "$EH_API_KEY"

# ─────────────────────────────────────────────────────────────────────────
stage "Discover the field map + structural IDs"
say "Reading the client's Connecteam fields and Employment Hero IDs..."
npm run discover -- --client self
say ""
warn "Now open clients/self/field-map.json and check EVERY mapped field ID,"
warn "resolve any TODO, and confirm the enum maps (gender / state / employmentType)."
pause "Press Enter when the field map is tuned."
for pair in "businessId:EH_BUSINESS_ID" "payScheduleId:EH_PAY_SCHEDULE_ID" "locationId:EH_LOCATION_ID"; do
  jkey="${pair%%:*}"; env_k="${pair##*:}"
  v=$(node -e "console.log((require('./clients/self/field-map.json').employmentHero||{}).$jkey||'')")
  if [[ -z "$v" || "$v" == "TODO" ]]; then
    ask "$env_k" "Enter $env_k:"
    v="${!env_k}"
  fi
  write_env "$env_k" "$v"
  set_jsonc "$env_k" "$v"
done
say "Running the test suite..."
npm test
say "Tests pass."

# ─────────────────────────────────────────────────────────────────────────
stage "Provision Cloudflare resources"
confirm "Create a D1 database and two Queues on this Cloudflare account now?" || { warn "Aborted."; exit 1; }
db_out=$(wr d1 create eh-webhook 2>&1 || true)
printf '%s\n' "$db_out" | sed 's/^/  /'
db_id=$(printf '%s' "$db_out" | grep -oiE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
if [[ -z "$db_id" ]]; then
  db_id=$(wr d1 list --json 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const d=JSON.parse(s);const m=(Array.isArray(d)?d:d.result||[]).find(x=>x.name==="eh-webhook");console.log(m?m.uuid||m.database_id||"":"")}catch(e){console.log("")}})')
fi
[[ -n "$db_id" ]] && set_jsonc database_id "$db_id" || warn "Put the D1 database_id into wrangler.jsonc by hand."
say "Applying migrations to the remote database..."
wr d1 migrations apply eh-webhook --remote
wr queues create eh-webhook-sync 2>&1 | sed 's/^/  /' || true
wr queues create eh-webhook-dlq  2>&1 | sed 's/^/  /' || true

# ─────────────────────────────────────────────────────────────────────────
stage "Push secrets + deploy"
put_secret CT_API_KEY "$CT_API_KEY"
put_secret EH_API_KEY "$EH_API_KEY"
put_secret CT_WEBHOOK_SECRET "$CT_WEBHOOK_SECRET"
say "Deploying..."
deploy_out=$(wr deploy 2>&1)
printf '%s\n' "$deploy_out" | sed 's/^/  /'
WORKER_URL=$(printf '%s' "$deploy_out" | grep -oE 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -1)
if [[ -n "$WORKER_URL" ]]; then
  say "Health check:"
  curl -fsS "$WORKER_URL/health" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const h=JSON.parse(s);console.log("   ok:",h.ok,"| d1:",h.d1,"| fieldMap:",h.fieldMap)})' \
    || warn "/health did not return 200 - inspect: $WORKER_URL/health"
else
  warn "Could not read the deployed URL from wrangler output - check the dashboard."
fi

# ─────────────────────────────────────────────────────────────────────────
stage "Register the Connecteam webhook"
say "Registers the user_updated webhook so profile edits sync after go-live."
WEBHOOK_TARGET="${WORKER_URL:-https://<your-worker>.workers.dev}/webhook"
note "URL:    $WEBHOOK_TARGET"
note "Event:  users / user_updated"
say ""
say "The signing secret (secretKey) can ONLY be set via the API - the Connecteam"
say "UI has no field for it, and the Worker rejects every unsigned delivery with"
say "401. So the wizard registers it here rather than sending you to the UI."
if [[ -n "${WORKER_URL:-}" ]]; then
  reg=$(ct_api_post "/settings/v1/webhooks" "$(printf '{"name":"EH Payroll Sync (profile updates)","url":"%s","featureType":"users","eventTypes":["user_updated"],"secretKey":"%s"}' "$WEBHOOK_TARGET" "$CT_WEBHOOK_SECRET")")
  wid=$(printf '%s' "$reg" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{console.log(JSON.parse(s).data?.id||"")}catch(e){console.log("")}})')
  if [[ -n "$wid" ]]; then
    printf '  %s✓ registered%s webhook id %s\n' "$GREEN" "$RESET" "$wid"
  else
    warn "could not confirm the webhook registered. Response:"
    printf '%s\n' "$reg" | sed 's/^/    /'
    SKIPPED+=("Connecteam webhook - register by API: POST /settings/v1/webhooks (see docs/RUNBOOK.md step 6)")
  fi
else
  warn "no deployed URL captured - register the webhook by hand once the Worker is live (docs/RUNBOOK.md step 6)."
  SKIPPED+=("Connecteam webhook registration (no Worker URL was captured)")
fi

# Show the webhook exactly as Connecteam now has it, so a wrong URL or a
# disabled toggle is visible here rather than a mystery later.
say ""
say "Connecteam's registered webhooks for this account:"
ct_api "/settings/v1/webhooks" | node -e '
  let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
    try {
      const d = JSON.parse(s);
      const list = d.data?.webhooks || d.data || d.webhooks || [];
      if (!Array.isArray(list) || list.length === 0) {
        console.log("   (none returned - inspect GET /settings/v1/webhooks by hand)"); return;
      }
      for (const w of list) {
        const enabled = w.enabled ?? w.isEnabled ?? w.active ?? w.status ?? "?";
        const events = (w.eventTypes || w.events || []).join(",") || "?";
        console.log("   ", w.id || w.webhookId || "?", " ", w.url || w.targetUrl || "?", " events:", events, " enabled:", enabled);
      }
    } catch (e) { console.log("   (could not parse the webhook list)"); }
  })'

# Close the loop: prove Connecteam is actually delivering to the Worker now,
# instead of finding out later. /health counts accepted (202) and rejected
# (401) user_updated deliveries.
if [[ -n "${WORKER_URL:-}" ]] && confirm "Do a live delivery check now (edit a test profile while the wizard watches)?"; then
  before=$(health_num webhookAccepted)
  rej_before=$(health_num webhookRejected)
  if [[ ! "$before" =~ ^[0-9]+$ || ! "$rej_before" =~ ^[0-9]+$ ]]; then
    warn "couldn't read $WORKER_URL/health to baseline the check - skipping."
    warn "verify by hand: edit a test profile, then re-check $WORKER_URL/health (ops.webhookAccepted)."
    SKIPPED+=("Confirm the first webhook delivery (docs/RUNBOOK.md 'Verify')")
  else
    say ""
    step "Now edit ANY mapped field on a TEST user's Connecteam profile and save it."
    printf '  %swaiting up to 90s for the delivery%s ' "$DIM" "$RESET"
    result="" ; waited=0
    while (( waited < 90 )); do
      sleep 5 ; waited=$(( waited + 5 )) ; printf '.'
      if (( $(health_num webhookAccepted) > before ));     then result="ok";       break; fi
      if (( $(health_num webhookRejected) > rej_before )); then result="rejected"; break; fi
    done
    printf '\n'
    case "$result" in
      ok)
        printf '  %s✓ the Worker accepted a profile update from Connecteam (202)%s\n' "$GREEN" "$RESET"
        say "The webhook path is live." ;;
      rejected)
        warn "a delivery ARRIVED but was rejected (401): the secretKey Connecteam sends"
        warn "does not match CT_WEBHOOK_SECRET. Delete the webhook in Connecteam and"
        warn "re-run this stage to re-register it with the current secret."
        SKIPPED+=("Webhook secret mismatch - re-register the Connecteam webhook (docs/RUNBOOK.md step 6)") ;;
      *)
        warn "no delivery seen in 90s. Usual causes:"
        note "  - the registered URL is not exactly $WEBHOOK_TARGET"
        note "  - the webhook shows enabled:false above (toggle it on in Connecteam)"
        note "  - the edited field isn't mapped, or it was the admin-only side of the pack"
        say  "See raw deliveries with:  npx wrangler tail --format pretty   then edit a profile again."
        SKIPPED+=("Confirm the first webhook delivery (docs/RUNBOOK.md 'Verify')") ;;
    esac
  fi
fi
say ""
say "The signature scheme (header x-webhook-secret, no HMAC) was confirmed in"
say "src/connecteam/signature.ts during #22."

finish
say "Next: approve a test onboarding pack and watch the employee appear in Employment Hero within ~1 minute."
say "Ongoing updates: scripts/update.sh"
