#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


ENV_FILE=".dev.vars"
TOTAL_STAGES=13

# ── extra helpers (below the marker, wizard-specific) ─────────────────────

# Readability helpers (#64): every stage reads why -> what you'll do -> the
# work -> what's next, with blank lines between the blocks.

# why "line" ... : the stage's purpose in plain language.
why() {
  printf '\n  %sWhy this step%s\n' "$BOLD" "$RESET"
  local l; for l in "$@"; do printf '    %s\n' "$l"; done
}

# todo "action" ... : numbered list of what the person will do in this stage.
todo() {
  printf '\n  %sWhat you'"'"'ll do%s\n' "$BOLD" "$RESET"
  local i=1 l line first
  for l in "$@"; do
    first=1
    # Wrap at 76 columns, continuation lines under the text, not the number.
    while IFS= read -r line; do
      if [[ -n "$first" ]]; then printf '    %s%d.%s %s\n' "$BLUE" "$i" "$RESET" "$line"; first=""
      else printf '       %s\n' "$line"; fi
    done < <(printf '%s\n' "$l" | fold -s -w 69 | sed 's/ *$//')
    i=$((i + 1))
  done
  printf '\n'
}

# ok "msg" / fail "msg": a green success line and a red failure line, distinct
# from warn's yellow.
ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# next_up "text": how this stage leads into the next one.
next_up() { printf '\n  %sNext: %s%s\n' "$DIM" "$1" "$RESET"; }

# save KEY VALUE "label" [jsonc]: store a value (and, with "jsonc", the
# wrangler.jsonc var of the same name) behind one plain line. The file names
# stay in the end-of-wizard summary for the integrator.
save() {
  write_env "$1" "$2" >/dev/null
  if [[ "${4:-}" == "jsonc" ]]; then set_jsonc "$1" "$2" >/dev/null; fi
  ok "Saved $3."
}

# run_tests: the test suite as one line; its full output only if it fails.
run_tests() {
  local out n
  if out=$(env -u FORCE_COLOR NO_COLOR=1 npm test 2>&1); then
    n=$(printf '%s\n' "$out" | sed -n 's/.*Tests  *\([0-9][0-9]*\) passed.*/\1/p' | tail -1)
    ok "All ${n:-the} checks passed - the settings fit together."
  else
    fail "Some checks failed - the field map or settings need fixing:"
    printf '%s\n' "$out" | tail -40 | sed 's/^/    /'
    exit 1
  fi
}

# set_jsonc KEY VALUE: replace the first  "KEY": "..."  in wrangler.jsonc.
# Plain IDs / UUIDs / a workers.dev URL only - no awk-sub metacharacters.
set_jsonc() {
  local key="$1" value="$2" tmp
  tmp=$(mktemp)
  awk -v k="\"$key\":" -v v="$value" '
    !done && index($0, k) { sub(/: *"[^"]*"/, ": \"" v "\""); done=1 }
    { print }
  ' wrangler.jsonc > "$tmp" && mv "$tmp" wrangler.jsonc
  printf '  %s✓ set%s wrangler.jsonc %s\n' "$GREEN" "$RESET" "$key"
}

# wr: run wrangler via npx, streaming output.
wr() { npx --yes wrangler "$@"; }

# ct_api PATH: GET the Connecteam API with the captured key.
ct_api() { curl -sS -H "X-API-KEY: $CT_API_KEY" -H "accept: application/json" "https://api.connecteam.com$1"; }

# ct_api_post PATH JSON: POST to the Connecteam API with the captured key.
ct_api_post() {
  curl -sS -X POST -H "X-API-KEY: $CT_API_KEY" -H "content-type: application/json" \
    -H "accept: application/json" -d "$2" "https://api.connecteam.com$1"
}

# ct_api_put PATH JSON / ct_api_delete PATH: the same, for updates and deletes.
ct_api_put() {
  curl -sS -X PUT -H "X-API-KEY: $CT_API_KEY" -H "content-type: application/json" \
    -H "accept: application/json" -d "$2" "https://api.connecteam.com$1"
}
ct_api_delete() {
  curl -sS -X DELETE -H "X-API-KEY: $CT_API_KEY" -H "accept: application/json" "https://api.connecteam.com$1"
}

# put_secret NAME VALUE: pipe a value into `wrangler secret put` (no echo).
put_secret() {
  printf '%s' "$2" | wr secret put "$1" >/dev/null \
    && printf '  %s✓ set%s Cloudflare secret %s\n' "$GREEN" "$RESET" "$1" \
    || warn "could not set secret $1 - run: printf %%s '<value>' | npx wrangler secret put $1"
}

# health_num KEY: print the deployed Worker's /health ops.KEY as an integer
# (0 if the field is absent or /health is unreachable). Needs $WORKER_URL.
health_num() {
  curl -fsS "${WORKER_URL}/health" 2>/dev/null | node -e '
    const key = process.argv[1];
    let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
      try { process.stdout.write(String(Number((JSON.parse(s).ops || {})[key] || 0))); }
      catch (e) { process.stdout.write("0"); }
    });' "$1" 2>/dev/null || printf '0'
}

# health_str KEY: print the deployed Worker's /health ops.KEY as a string
# (empty if absent, null or /health is unreachable). Needs $WORKER_URL.
health_str() {
  curl -fsS "${WORKER_URL}/health" 2>/dev/null | node -e '
    const key = process.argv[1];
    let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
      try { const v = (JSON.parse(s).ops || {})[key]; process.stdout.write(v == null ? "" : String(v)); }
      catch (e) { process.stdout.write(""); }
    });' "$1" 2>/dev/null || printf ''
}

# ── prerequisites (before the banner, so a missing tool fails fast) ───────
for _c in node npm npx git curl; do
  command -v "$_c" >/dev/null 2>&1 || { printf 'missing required tool: %s\n' "$_c" >&2; exit 1; }
done
grep -q '"name": "eh-webhook"' package.json 2>/dev/null \
  || { printf 'run this from the EH_Webhook repo root\n' >&2; exit 1; }
[[ -d node_modules ]] || { printf 'installing dependencies...\n'; npm install; }

banner "EH_Webhook - client deployment"

# ─────────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
why "The sync runs as a small program (a \"Worker\") on Cloudflare, in your own" \
    "account, so you own it and everything it stores. It needs the Workers Paid" \
    "plan (about US\$5 a month) because it uses Cloudflare Queues."
todo "Sign up or sign in on the page that opens, and make sure the account is on Workers Paid." \
     "Sign this computer in to that account when the next browser tab opens." \
     "Check that the account name shown here is the right one."
open_url "https://dash.cloudflare.com/?to=/:account/workers/plans"
confirm "Do you now have a Cloudflare account on the Workers Paid plan?" || { fail "Create an account and/or upgrade to Workers Paid on the page above, then run the wizard again."; exit 1; }
printf '\n'
say "Signing this computer in to Cloudflare (a browser tab may open)..."
wr whoami >/dev/null 2>&1 || wr login
wr whoami | sed 's/^/  /'
printf '\n'
confirm "Is the account above the right one?" || { fail "Run 'npx wrangler logout', then run the wizard again."; exit 1; }
next_up "Connecteam - the API key the sync uses to read your onboarding packs."

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: API key"
why "The sync uses this key to read approved onboarding packs and to send" \
    "messages in Connecteam. It is stored only on your Cloudflare account."
todo "On the page that opens (Connecteam: Integrations > API Keys), create a new API key." \
     "Give it read access to users and onboarding, and write access to chat and to custom fields (stages 7 and 8 use that)." \
     "Paste it here. It won't show as you type."
open_url "https://app.connecteam.com/#/settings/integrations/api"
printf '\n'
ask_secret CT_API_KEY "Paste the Connecteam API key:"
save CT_API_KEY "$CT_API_KEY" "the Connecteam API key"
next_up "the sender name on the sync's messages."

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: custom publisher"
why "Every message the sync sends - to an employee or to your admins - comes" \
    "from this sender, so it reads as \"EH Sync\" rather than one of your staff."
todo "In Connecteam, open Settings > Custom Publishers." \
     "Create one called \"EH Sync\" and copy its number (the publisher ID)." \
     "Paste it here."
open_url "https://app.connecteam.com/#/settings"
printf '\n'
ask CT_CUSTOM_PUBLISHER_ID "Paste the custom publisher ID:"
save CT_CUSTOM_PUBLISHER_ID "$CT_CUSTOM_PUBLISHER_ID" "the sender" jsonc
next_up "the chat channel for your payroll admins."

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: alerts channel"
why "When a payroll admin needs to finish something by hand (for example a" \
    "non-resident tax scale), or something goes wrong, the sync posts a message" \
    "here. Employees never see this channel; their messages go to them directly."
todo "In Connecteam, create a chat channel called \"EH Sync Alerts\"." \
     "Add the payroll admins who should act on its messages." \
     "Come back here and paste its ID from the list below."
pause "Press Enter once the channel exists."
printf '\n'
say "Chat channels on this account:"
CHANNEL_LIST=$(ct_api "/chat/v1/conversations" \
  | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const c=(JSON.parse(s).data?.conversations)||[];if(!c.length){console.log("   (none found)");return}for(const x of c)console.log("   ",x.id,"  ",x.title||x.name||"(untitled)")}catch(e){console.log("   (could not list - open GET /chat/v1/conversations by hand)")}})')
printf '%s\n\n' "$CHANNEL_LIST"
if [[ "$CHANNEL_LIST" == *"(none found)"* ]]; then
  warn "No chat channels found - create \"EH Sync Alerts\" first, then come back here."
fi
ask ADMIN_CONNECTEAM_CHANNEL_ID "Paste the \"EH Sync Alerts\" channel ID:"
save ADMIN_CONNECTEAM_CHANNEL_ID "$ADMIN_CONNECTEAM_CHANNEL_ID" "the alerts channel" jsonc
next_up "the onboarding pack your new employees fill in."

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam: onboarding pack"
why "When an admin approves a new employee's onboarding pack, the sync creates" \
    "that employee in Employment Hero. It needs to know which pack to watch."
todo "Make sure the pack exists in Connecteam (HR & Skills > Onboarding) and has an approval step." \
     "Pick it from the list below and paste its number."
pause "Press Enter once the onboarding pack exists."
printf '\n'
say "Onboarding packs on this account:"
PACK_LIST=$(ct_api "/onboarding/v1/packs" \
  | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const p=(JSON.parse(s).data?.packs)||(JSON.parse(s).data)||[];if(!p.length){console.log("   (none found)");return}for(const x of p)console.log("    "+String(x.id||x.packId)+"    "+(x.name||"(unnamed)"))}catch(e){console.log("   (could not list - open GET /onboarding/v1/packs by hand)")}})')
printf '%s\n\n' "$PACK_LIST"
if [[ "$PACK_LIST" == *"(none found)"* ]]; then
  warn "No onboarding packs found - create one with an approval step, then come back here."
fi
ask CT_ONBOARDING_PACK_ID "Paste the onboarding pack ID:"
save CT_ONBOARDING_PACK_ID "$CT_ONBOARDING_PACK_ID" "the onboarding pack" jsonc
# Keep an existing secret on a re-run: a new one would no longer match the
# webhook Connecteam already has, and every delivery would get a 401 (#82).
if CT_WEBHOOK_SECRET=$(_existing CT_WEBHOOK_SECRET) && [[ -n "$CT_WEBHOOK_SECRET" ]]; then
  ok "Kept the existing webhook secret (the last stage gives it to Connecteam)."
else
  CT_WEBHOOK_SECRET=$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')
  write_env CT_WEBHOOK_SECRET "$CT_WEBHOOK_SECRET" >/dev/null
  ok "Created a webhook secret (the last stage gives it to Connecteam)."
fi
next_up "Employment Hero - the API key the sync uses to create employees."

# ─────────────────────────────────────────────────────────────────────────
stage "Employment Hero: API key"
why "The sync uses this key to create and update employees in Employment Hero" \
    "Payroll. Like the Connecteam key, it is stored only on your Cloudflare account."
todo "On the page that opens, sign in to Employment Hero Payroll and open My Account > Security > API Key." \
     "Turn OFF the employee self-setup email for the business: the sync fills in each employee's details itself, so the email would only confuse them." \
     "Paste the key here. It won't show as you type."
open_url "https://api.yourpayroll.com.au"
printf '\n'
ask_secret EH_API_KEY "Paste the Employment Hero API key:"
save EH_API_KEY "$EH_API_KEY" "the Employment Hero API key"
next_up "your award, if you pay under one."

# ─────────────────────────────────────────────────────────────────────────
stage "Award classifications"
why "Employment Hero holds your award and its classifications (for example" \
    "\"General Retail Casual L3\"). Connecteam doesn't know about awards, so this" \
    "copies them into an admin-only Connecteam dropdown. Your admins then pick" \
    "each employee's classification, and Employment Hero works out the pay rate."
printf '\n'
if confirm "Does this business pay employees under an award"; then
  todo "In Employment Hero, install the award(s) you pay under, if you haven't yet. Choosing an award is a payroll and legal decision, so this part stays manual." \
       "Press Enter, and the wizard copies the classifications into Connecteam."
  pause "Press Enter once your award is installed in Employment Hero."
  printf '\n'
  until npm run --silent provision-classification-field 2>&1 | sed 's/^./  &/'; do
    printf '\n'
    fail "The award import didn't finish - the message above says why."
    confirm "Fix that, then try again" || { warn "Skipped. Run it later with: npm run provision-classification-field"; break; }
  done
  printf '\n'
  note "For your admins: set each employee's \"EH Pay Rate Template\" on their Connecteam"
  note "profile. The Pay-run settings stage connects it to the sync."
else
  note "Skipped. Each employee's pay rate can come from Connecteam instead (Pay-run settings stage)."
fi
next_up "check every Connecteam field the sync reads."

# ─────────────────────────────────────────────────────────────────────────
stage "Connecteam field check"
why "The sync reads 27 Connecteam fields (TFN, bank, super, tax answers," \
    "emergency contact...) plus the award dropdown. This checks each one exists," \
    "has the right type and dropdown options, and says how to fix anything that doesn't."
printf '\n'
field_check() { npm run --silent field-check && fc_rc=0 || fc_rc=$?; [[ $fc_rc -ne 1 ]] || exit 1; }
field_check
plan=$(npm run --silent create-fields -- --dry-run) || { printf '%s\n' "$plan" | sed 's/^/  /'; exit 1; }
if ! printf '%s' "$plan" | grep -q "Nothing to create"; then
  printf '\n'
  printf '%s\n' "$plan" | sed 's/^/  /'
  printf '\n'
  if confirm "Create the missing fields in Connecteam now"; then
    until npm run --silent create-fields; do
      fail "Some fields weren't created - the message above says why."
      confirm "Try again (only the missing ones are created)" || break
    done
    todo "In Connecteam, open your onboarding pack and add every field ticked [ ] above. This has no API, so it has to be done by hand."
    pause "Press Enter once they're all in the pack, to check again."
    printf '\n'
    field_check
  fi
fi
while [[ $fc_rc -eq 2 ]]; do
  printf '\n'
  fail "A required field is missing or the wrong type (marked above). The sync can't"
  fail "create employees in Employment Hero until it's fixed."
  pause "Fix it in Connecteam, then press Enter to check again (Ctrl-C to stop)."
  printf '\n'
  field_check
done
printf '\n'
note "One thing this can't check: that every field is in your onboarding pack."
note "A field that isn't in the pack is never asked, so it is always blank."
pause "Press Enter when you've confirmed the pack includes them."
next_up "match your Connecteam fields to Employment Hero's."

# ─────────────────────────────────────────────────────────────────────────
stage "Field map"
why "The field map tells the sync which Connecteam field fills which Employment" \
    "Hero field (for example \"TFN\" fills the tax file number). It is built from" \
    "your fields, so you don't have to write it."
printf '\n'
discover_out=$(npm run --silent discover -- --client self --from-wizard) || { printf '%s\n' "$discover_out" | sed 's/^/  /'; exit 1; }
printf '%s\n' "$discover_out" | sed '$d' | sed 's/^./  &/'
map_status=$(printf '%s\n' "$discover_out" | tail -n1 | sed -n 's/^MAP_STATUS=//p')
printf '\n'
if [[ "$map_status" == "changed" ]]; then
  warn "Your field map was kept, but your Connecteam fields changed since it was set up."
  todo "Copy the changes you want from clients/self/field-map.draft.json into clients/self/field-map.json (or ask your integrator)."
  pause "Press Enter when that's done."
else
  ok "Field map ready."
fi
v=$(node -e "console.log((require('./clients/self/field-map.json').employmentHero||{}).businessId||'')")
if [[ -z "$v" || "$v" == "TODO" ]]; then
  ask EH_BUSINESS_ID "Enter the Employment Hero business ID:"
  v="$EH_BUSINESS_ID"
fi
save EH_BUSINESS_ID "$v" "the Employment Hero business" jsonc
next_up "pay-run settings."

# ─────────────────────────────────────────────────────────────────────────
stage "Pay-run settings"
why "Employment Hero needs a pay schedule, location and pay category for each" \
    "employee, plus where their pay rate comes from. Without them, every employee" \
    "lands in Employment Hero as Incomplete. You pick each one from your own lists."
printf '\n'
npm run --silent pay-defaults -- --client self
printf '\n'
say "Checking that the field map and settings fit together..."
run_tests
next_up "set up the sync's storage on Cloudflare."

# ─────────────────────────────────────────────────────────────────────────
stage "Provision Cloudflare resources"
why "The sync keeps a small notebook (a database) of which Connecteam person is" \
    "which Employment Hero employee - no TFNs or bank details - and two queues:" \
    "an in-tray for work, and a problem tray so nothing is silently lost."
printf '\n'
confirm "Create the database and the two queues on this Cloudflare account now?" || { warn "Stopped here. Nothing was created on Cloudflare."; exit 1; }
db_out=$(wr d1 create eh-webhook 2>&1 || true)
printf '%s\n' "$db_out" | sed 's/^/  /'
db_id=$(printf '%s' "$db_out" | grep -oiE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
if [[ -z "$db_id" ]]; then
  db_id=$(wr d1 list --json 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const d=JSON.parse(s);const m=(Array.isArray(d)?d:d.result||[]).find(x=>x.name==="eh-webhook");console.log(m?m.uuid||m.database_id||"":"")}catch(e){console.log("")}})')
fi
[[ -n "$db_id" ]] && set_jsonc database_id "$db_id" || warn "Put the D1 database_id into wrangler.jsonc by hand."
say "Applying migrations to the remote database..."
wr d1 migrations apply eh-webhook --remote
wr queues create eh-webhook-sync 2>&1 | sed 's/^/  /' || true
wr queues create eh-webhook-dlq  2>&1 | sed 's/^/  /' || true
next_up "put the sync live."

# ─────────────────────────────────────────────────────────────────────────
stage "Push secrets + deploy"
why "This puts the sync live on your Cloudflare account and stores the two API" \
    "keys and the webhook secret there, where only the sync can read them."
printf '\n'
put_secret CT_API_KEY "$CT_API_KEY"
put_secret EH_API_KEY "$EH_API_KEY"
put_secret CT_WEBHOOK_SECRET "$CT_WEBHOOK_SECRET"
say "Deploying..."
deploy_out=$(wr deploy 2>&1)
printf '%s\n' "$deploy_out" | sed 's/^/  /'
WORKER_URL=$(printf '%s' "$deploy_out" | grep -oE 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -1)
if [[ -n "$WORKER_URL" ]]; then
  say "Health check:"
  curl -fsS "$WORKER_URL/health" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const h=JSON.parse(s);console.log("   ok:",h.ok,"| d1:",h.d1,"| fieldMap:",h.fieldMap)})' \
    || warn "/health did not return 200 - inspect: $WORKER_URL/health"
else
  warn "Could not read the deployed URL from wrangler output - check the dashboard."
fi
next_up "connect Connecteam's profile updates to the sync."

# ─────────────────────────────────────────────────────────────────────────
stage "Register the Connecteam webhook"
why "So that an employee's later profile edits reach Employment Hero within" \
    "seconds, Connecteam tells the sync whenever a profile changes (a \"webhook\")." \
    "Only the API can give it the secret the sync checks, so the wizard does this."
WEBHOOK_TARGET="${WORKER_URL:-https://<your-worker>.workers.dev}/webhook"
printf '\n'
note "URL:    $WEBHOOK_TARGET"
note "Event:  users / user_updated"
printf '\n'
if [[ -n "${WORKER_URL:-}" ]]; then
  wh_body=$(printf '{"name":"EH Payroll Sync (profile updates)","url":"%s","featureType":"users","eventTypes":["user_updated"],"secretKey":"%s","isDisabled":false}' "$WEBHOOK_TARGET" "$CT_WEBHOOK_SECRET")
  # Re-running must not add a second webhook (#82): update one already pointing
  # at this Worker - same secret as the Worker, turned on - and offer to delete
  # any extras.
  existing_ids=$(ct_api "/settings/v1/webhooks" | node -e '
    let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
      try {
        const list = JSON.parse(s).data?.webhooks || [];
        console.log(list.filter(w => w.url === process.argv[1] && w.featureType === "users").map(w => w.id).join(" "));
      } catch (e) { console.log(""); }
    })' "$WEBHOOK_TARGET")
  read -r -a existing <<< "$existing_ids"
  if (( ${#existing[@]} > 0 )); then
    wid="${existing[0]}"
    upd=$(ct_api_put "/settings/v1/webhooks/$wid" "$wh_body")
    wh_updated=""
    if printf '%s' "$upd" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const j=JSON.parse(s);process.exit(j.detail||j.error?1:0)}catch(e){process.exit(1)}})'; then
      wh_updated=1
      printf '  %s✓ updated%s the existing webhook id %s (current secret, turned on) - no new one added\n' "$GREEN" "$RESET" "$wid"
    else
      warn "could not update the existing webhook $wid. Response:"
      printf '%s\n' "$upd" | sed 's/^/    /'
      SKIPPED+=("Connecteam webhook $wid - update its secretKey to CT_WEBHOOK_SECRET: PUT /settings/v1/webhooks/$wid (docs/RUNBOOK.md step 6)")
    fi
    # Only once the update worked: until then an extra may be the one that works.
    if [[ -n "$wh_updated" ]] && (( ${#existing[@]} > 1 )); then
      extras=("${existing[@]:1}")
      warn "${#extras[@]} more webhook(s) point at this Worker (ids ${extras[*]}), from earlier runs."
      if confirm "Delete the extra webhook(s) ${extras[*]} in Connecteam"; then
        for x in "${extras[@]}"; do
          ct_api_delete "/settings/v1/webhooks/$x" >/dev/null && printf '  %s✓ deleted%s webhook id %s\n' "$GREEN" "$RESET" "$x"
        done
      fi
    fi
  else
    reg=$(ct_api_post "/settings/v1/webhooks" "$wh_body")
    wid=$(printf '%s' "$reg" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{console.log(String(JSON.parse(s).data?.id??""))}catch(e){console.log("")}})')
    if [[ -n "$wid" ]]; then
      printf '  %s✓ registered%s webhook id %s\n' "$GREEN" "$RESET" "$wid"
    else
      warn "could not confirm the webhook registered. Response:"
      printf '%s\n' "$reg" | sed 's/^/    /'
      SKIPPED+=("Connecteam webhook - register by API: POST /settings/v1/webhooks (see docs/RUNBOOK.md step 6)")
    fi
  fi
else
  warn "no deployed URL captured - register the webhook by hand once the Worker is live (docs/RUNBOOK.md step 6)."
  SKIPPED+=("Connecteam webhook registration (no Worker URL was captured)")
fi

# Show the webhook exactly as Connecteam now has it, so a wrong URL or a
# disabled toggle is visible here rather than a mystery later. Connecteam's
# list (GET /settings/v1/webhooks) marks a turned-off webhook with
# `isDisabled: true` (#68). The last line is a machine-readable summary.
say ""
say "Connecteam's registered webhooks for this account:"
wh_out=$(ct_api "/settings/v1/webhooks" | node -e '
  const target = process.argv[1];
  let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
    let ours = [];
    try {
      const list = JSON.parse(s).data?.webhooks || [];
      if (list.length === 0) console.log("   (none returned - inspect GET /settings/v1/webhooks by hand)");
      for (const w of list) {
        const mine = w.url === target;
        if (mine) ours.push(w);
        const state = w.isDisabled === true ? "DISABLED" : w.isDisabled === false ? "enabled" : "enabled: ?";
        console.log(`   ${mine ? "->" : "  "} ${w.id}  ${w.url}  events: ${(w.eventTypes || []).join(",") || "?"}  ${state}`);
      }
      if (ours.length) console.log("   (-> = this Worker)");
    } catch (e) { console.log("   (could not parse the webhook list)"); }
    const status = ours.length === 0 ? "missing" : ours.every(w => w.isDisabled === true) ? "disabled" : "ok";
    console.log(`STATUS=${status} COUNT=${ours.length} DISABLED_IDS=${ours.filter(w => w.isDisabled === true).map(w => w.id).join(",")}`);
  })' "$WEBHOOK_TARGET")
printf '%s\n' "$wh_out" | sed '$d'
wh_summary=$(printf '%s\n' "$wh_out" | tail -n1)
wh_status=$(printf '%s' "$wh_summary" | sed -n 's/.*STATUS=\([a-z]*\).*/\1/p')
wh_count=$(printf '%s' "$wh_summary" | sed -n 's/.*COUNT=\([0-9]*\).*/\1/p')
wh_disabled=$(printf '%s' "$wh_summary" | sed -n 's/.*DISABLED_IDS=\(.*\)$/\1/p')
if [[ "$wh_status" == "disabled" ]]; then
  warn "The webhook for this Worker is turned OFF in Connecteam (id $wh_disabled), so profile"
  warn "edits won't reach the sync. Turn it on in Connecteam's webhook settings."
  pause "Press Enter once it's turned on."
elif [[ -n "$wh_disabled" ]]; then
  warn "Webhook id(s) $wh_disabled for this Worker are turned off; at least one other is on."
fi
if [[ "${wh_count:-0}" -gt 1 ]]; then
  warn "$wh_count webhooks point at this Worker (from re-running this stage). Each edit is"
  warn "delivered once per webhook; the sync coalesces them, but delete the extras in Connecteam."
fi
if [[ "$wh_status" == "missing" && -n "${WORKER_URL:-}" ]]; then
  warn "No webhook points at $WEBHOOK_TARGET - profile edits won't sync. See docs/RUNBOOK.md step 6."
fi

# Close the loop: prove Connecteam is actually delivering to the Worker now,
# instead of finding out later. /health counts accepted (202) and rejected
# (401) user_updated deliveries.
if [[ -n "${WORKER_URL:-}" ]] && confirm "Do a live delivery check now (edit a test profile while the wizard watches)?"; then
  before=$(health_num webhookAccepted)
  rej_before=$(health_num webhookRejected)
  if [[ ! "$before" =~ ^[0-9]+$ || ! "$rej_before" =~ ^[0-9]+$ ]]; then
    warn "couldn't read $WORKER_URL/health to baseline the check - skipping."
    warn "verify by hand: edit a test profile, then re-check $WORKER_URL/health (ops.webhookAccepted)."
    SKIPPED+=("Confirm the first webhook delivery (docs/RUNBOOK.md 'Verify')")
  else
    say ""
    step "Now edit ANY mapped field on a TEST user's Connecteam profile and save it."
    printf '  %swaiting up to 90s for the delivery%s ' "$DIM" "$RESET"
    result="" ; waited=0
    while (( waited < 90 )); do
      sleep 5 ; waited=$(( waited + 5 )) ; printf '.'
      if (( $(health_num webhookAccepted) > before ));     then result="ok";       break; fi
      if (( $(health_num webhookRejected) > rej_before )); then result="rejected"; break; fi
    done
    printf '\n'
    case "$result" in
      ok)
        printf '  %s✓ the Worker accepted a profile update from Connecteam (202)%s\n' "$GREEN" "$RESET"
        say "The webhook path is live." ;;
      rejected)
        warn "a delivery ARRIVED but was rejected (401): the secretKey Connecteam sends"
        warn "does not match CT_WEBHOOK_SECRET. Re-run the wizard: its webhook stage now"
        warn "updates the existing webhook with the current secret (no new one is added)."
        SKIPPED+=("Webhook secret mismatch - re-run the wizard to update the Connecteam webhook's secret (docs/RUNBOOK.md step 6)") ;;
      *)
        warn "no delivery seen in 90s. Usual causes:"
        note "  - the registered URL is not exactly $WEBHOOK_TARGET"
        note "  - the webhook shows DISABLED above (turn it on in Connecteam's webhook settings)"
        note "  - the edited field isn't mapped, or it was the admin-only side of the pack"
        say  "See raw deliveries with:  npx wrangler tail --format pretty   then edit a profile again."
        SKIPPED+=("Confirm the first webhook delivery (docs/RUNBOOK.md 'Verify')") ;;
    esac
  fi
fi

# The approval sweep is a Cron Trigger, and Cloudflare can take up to 15
# minutes to start a new one after the first deploy (#69). Until it has run
# once, an approved employee won't appear in EH - don't promise "~1 minute".
sweep_at=""
if [[ -n "${WORKER_URL:-}" ]]; then
  sweep_at=$(health_str lastSweepOkAt)
  if [[ -z "$sweep_at" ]]; then
    say ""
    say "The Worker checks Connecteam for approved packs every minute, but on a first"
    say "deploy Cloudflare can take up to 15 minutes to start that check."
    if confirm "Wait here until the first check has run (up to 16 minutes)"; then
      printf '  %swaiting for the first check%s ' "$DIM" "$RESET"
      waited=0
      while (( waited < 960 )); do
        sleep 15 ; waited=$(( waited + 15 ))
        sweep_at=$(health_str lastSweepOkAt)
        [[ -n "$sweep_at" ]] && break
        (( waited % 60 == 0 )) && printf '%d min ' $(( waited / 60 )) || printf '.'
      done
      printf '\n'
      if [[ -n "$sweep_at" ]]; then
        printf '  %s✓ the first approval check ran (%s)%s\n' "$GREEN" "$sweep_at" "$RESET"
      else
        warn "the first check hasn't run after 16 minutes. Check $WORKER_URL/health:"
        warn "ops.lastSweepOkAt should show a time; if it stays empty, see docs/RUNBOOK.md 'Verify'."
        SKIPPED+=("Confirm the first approval check ran (ops.lastSweepOkAt on /health)")
      fi
    fi
  fi
fi

finish
if [[ -n "$sweep_at" ]]; then
  say "Next: approve a test onboarding pack; the employee appears in Employment Hero within ~1 minute."
else
  say "Next: approve a test onboarding pack. The first approval check can take up to 15 minutes"
  say "to start after a first deploy; once ops.lastSweepOkAt shows a time on"
  say "$WORKER_URL/health, approvals appear in Employment Hero within ~1 minute."
fi
say "Profile edits after that sync within seconds (the webhook)."
say "Ongoing updates: scripts/update.sh"
